### ISSUE TITLE
Implement G point status label

### ISSUE THREAD

**Issue by kokkonisd** [kokkonisd/pression#2]
Make a label that lets us know if the barycenter is inside the optimal area or not.

**Comment by lochej** [comment]
The optimal area (deadzone) should be customizable. There should be a slider or a spinbox in the GUI which allows you to dynamically scale the deadzone size.

The deadzone size radius should be calculated via the following technique:

Chaise.radius=(Chaise.ratio/2)*min(Chaise.getMaxPosX(),Chaise.getMaxPoxY()) 

This formula says that if the deadzone is in the center of the chair, then the area shouldn't be larger than the actual chair's dimensions.

or something like that. This could be a way of calculating it.

ratio is a value in [0,1] .
